config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  
  devise_for :users
  
  resources :books
  resources :users, only:[:index, :show, :edit, :update] 
  get "/home/about" => "homes#about"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
  belongs_to :user
  validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
   
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: {maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  protected

#名前でsign_in、メールと名前でsign_up
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
#ログイン後マイページに飛ぶ
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end
  
  def create
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render action: :index
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = User.find(current_user.id)
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
  def index
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! ,only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users =User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
    if @user != current_user
      render action: :show
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left_side.html.erb
    <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
    <table class="table">
      <tr>
        <td>name</td>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
    </table>
    <div class="row">
      <%= link_to edit_user_path(current_user.id), class:"btn btn-default btn-block col-xs-12" do %>
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      <% end %>
    </div>
    
    <h2>New book</h2>
    <%= form_with model: book, local:true do |f| %>
      <div class="row field">
        <label>Title</label>
        <%= f.text_field :title, class: "col-xs-12" %>
      </div>
      <div class="row field">
        <label>Opinion</label>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>
      <div class="row">
        <%= f.submit "Create Book", class: "btn btn-primary btn-block col-xs-12" %>
      </div>
    <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="error_message">
    <h3>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
    </h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= form_with model: @book, local:true do |f| %>
      <div class="row field">
        <label>Title</label>
        <%= f.text_field :title, class: "col-xs-12" %>
      </div>
      <div class="row field">
        <label>Opinion</label>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>
      <div class="row">
        <%= f.submit "Update Book", class: "btn btn-primary btn-block col-xs-12" %>
      </div>
    <% end %>
    <%= link_to "Show", book_path %>
    |
    <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="error_message">
    <h3>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
    </h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <!-- 左カラム -->
  <div class="col-xs-3">
    <%= render 'books/left_side', user: @user, book: @book %>
  </div>
  <!-- 左カラム終了 -->
  
  <!-- 右カラム -->
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </table>
  </div>
  
</div>

app/views/books/show.html.erb
<div class="row">
  <!-- 左カラム -->
  <div class="col-xs-3">
    <%= render 'books/left_side', user: @user, book: @book_new %>
  </div>
  <!-- 左カラム終了 -->
  
  <!-- 右カラム -->
  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table">
      <tr>
        <td>
          <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback:"no_image.jpg", size:'40x40' %><br>
          <%= link_to @book.user.name, user_path(@book.user_id) %>
        </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>
        <% if @book.user == current_user %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success btn-sm btn_txt_color" %></td>
          <td><%= link_to "Destroy", book_path(@book.id), class:"btn btn-danger btn-sm btn_txt_color", method: :delete,
          data: {confirm: "本当に削除しますか?"} %></td>
        <% end %>
      </tr>
    </table>
  </div>
  <!-- 右カラム終了 -->
</div>

app/views/homes/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers!</strong></h1>

app/views/homes/index.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h1>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong></h1>
    <p>In<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions,inpressions,and emotions</p>
    <p>about various books!</p>
    
    <!-- サインアップ/ログインボタン -->
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in home-btn" %>
    </div>
    <div class="row">
      <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up home-btn" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>

<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-static-top navbar-inverse navbar-custom">
      <div class="container">
        <div class=class="collapse navbar-collapse" id="navbarEexample">
          <span class="navbar-left">Bookers</span>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to " Users", users_path, class: "users glyphicon glyphicon-user" %></li>
              <li><%= link_to " Books", books_path, class: "books glyphicon glyphicon-book" %></li>
              <li><%= link_to "  logout", destroy_user_session_path, class: "logout glyphicon glyphicon-log-out", method: :delete %></li>
            <% else %>
              <li><%= link_to " Home", "/", class: "home glyphicon glyphicon-home" %></li>
              <li><%= link_to " About", "/home/about", class: "about glyphicon glyphicon-link" %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: "sign_up glyphicon glyphicon-edit" %></li>
              <li><%= link_to "  login", new_user_session_path, class: "sign_in glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </div>
      </div>
      
    </header>
    <div class="container">
      <%= yield %>
      <p class="pull-right">CopyRight Infratop.inc</p>
    </div>
    
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="error_message">
    <h3>
      <%= @user.errors.count %> errors prohibited this obj from being saved:
    </h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>User info</h2>

<%= form_with model:@user, local:true do |f| %>
  <div class="field">
    <label>Name</label>
  <%= f.text_field :name, autofocus: true, placeholder:"名前", class: "name", id:"inputName" %><br>
  </div>
  <div class="field">
    <label>Image</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  </div>
  <div class="field">
    <label>Introduction</label>
    <%= f.text_area :introduction, class:"introduction" %> <br>
  </div>
  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  
  <!-- 左カラム -->
  <div class="col-xs-3">
    <%= render 'books/left_side', user: @user, book: @book %>
  </div>
  <!-- 左カラム終了 -->
  
  <!-- 右カラム -->
  <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <!-- 右カラム終了 -->
</div>

app/views/users/show.html.erb
<div class="row">
  <!-- 左カラム -->
  <div class="col-xs-3">
    <%= render 'books/left_side', user: @user, book: @book %>
  </div>
  <!-- 左カラム終了 -->
  
  <!-- 右カラム -->
  <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <!-- 右カラム終了 -->
</div>